# Test against this version of Node.js
environment:
  nodejs_version: "0.10"

environment:
  matrix:
  # node.js
  - nodejs_version: "0.10"
  - nodejs_version: "0.8"

cache:
  - node_modules # local packages node_modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache # preserve npm-cache

# Install scripts. (runs after repo cloning)
install:
  # Fetch project submodules
  - git submodule update --init --recursive
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
