const fs = require('fs');
const path = require('path');

function loadConfig() {
  const configPath = path.join(__dirname, '..', '..', 'build', 'config.gypi');
  const config = fs.readFileSync(configPath, 'utf-8')
  return JSON.parse(config.replace(`# Do not edit. File was generated by node-gyp's "configure" step`, ''));
}

function loadProtagonist() {
  const configuration = loadConfig().target_defaults.default_configuration;
  return require(`../../build/${configuration}/protagonist`);
}

module.exports = loadProtagonist();
